#!/usr/bin/env python3
"""tools/voice/make_voice.py — records every line Barem speaks with Microsoft Edge's neural
Saudi voice (edge-tts) and writes game/js/voice-files.js, which maps each line to its clip.

    pip install edge-tts
    python3 tools/voice/make_voice.py            # records only the lines that have no clip yet
    python3 tools/voice/make_voice.py --all      # records everything again

The line list comes from tools/voice/lines.js (Node). Clips are saved as game/voice/<hash>.mp3,
named after the line itself, so editing a line in content.js records just that line again and
clips no longer used are deleted. Needs network access to speech.platform.bing.com.
Behind a TLS-inspecting proxy, set EDGE_TTS_CA to the proxy's CA bundle file.
"""
import asyncio, hashlib, json, os, ssl, subprocess, sys
import edge_tts
import edge_tts.communicate as ec

VOICE = os.environ.get('EDGE_TTS_VOICE', 'ar-SA-ZariyahNeural')   # warm Saudi female voice
RATE = os.environ.get('EDGE_TTS_RATE', '-8%')                       # a little slower, for young children
HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.normpath(os.path.join(HERE, '..', '..', 'game'))
OUT = os.path.join(GAME, 'voice')

if os.environ.get('EDGE_TTS_CA'):
    ec._SSL_CTX = ssl.create_default_context(cafile=os.environ['EDGE_TTS_CA'])

def clip_name(text):
    return hashlib.sha1(text.encode('utf-8')).hexdigest()[:12] + '.mp3'

async def record(text, path, sem):
    async with sem:
        for attempt in range(4):
            try:
                await edge_tts.Communicate(text, VOICE, rate=RATE).save(path + '.part')
                if os.path.getsize(path + '.part') < 800:
                    raise RuntimeError('empty clip')
                os.replace(path + '.part', path)
                print('ok  ', text)
                return True
            except Exception as e:                      # network hiccup: wait and try again
                err = e
                await asyncio.sleep(2 ** attempt)
        print('FAIL', text, '-', err, file=sys.stderr)
        return False

async def main():
    lines = json.loads(subprocess.check_output(['node', os.path.join(HERE, 'lines.js')]).decode('utf-8'))
    os.makedirs(OUT, exist_ok=True)
    redo = '--all' in sys.argv
    todo = [t for t in lines if redo or not os.path.exists(os.path.join(OUT, clip_name(t)))]
    sem = asyncio.Semaphore(4)
    ok = await asyncio.gather(*(record(t, os.path.join(OUT, clip_name(t)), sem) for t in todo))
    have = {t: 'voice/' + clip_name(t) for t in lines if os.path.exists(os.path.join(OUT, clip_name(t)))}
    used = {os.path.basename(p) for p in have.values()}
    for f in os.listdir(OUT):                          # clips for lines that no longer exist
        if f.endswith('.mp3') and f not in used:
            os.remove(os.path.join(OUT, f))
    with open(os.path.join(GAME, 'js', 'voice-files.js'), 'w', encoding='utf-8') as fh:
        fh.write('/* voice-files.js — recorded voice clips, generated by tools/voice/make_voice.py\n'
                 f'   ({VOICE}, rate {RATE}). Keys are the spoken text as normalised by voiceKey(). */\n'
                 "'use strict';\nconst VOICE_CLIPS = ")
        json.dump(have, fh, ensure_ascii=False, indent=0)
        fh.write(';\n')
    print(f'{len(have)} of {len(lines)} lines have a clip; {sum(not x for x in ok)} failed this run')
    return 0 if len(have) == len(lines) else 1

if __name__ == '__main__':
    sys.exit(asyncio.run(main()))
